name: Dump Entities from Baserow

on:
  schedule:
  - cron: "12 5 * * *"
  workflow_dispatch:

jobs:
  download:
    name: dump baserow
    runs-on: ubuntu-latest
    env:
      BASEROW_TOKEN: ${{secrets.BASEROW_TOKEN}}
      BASEROW_USER: ${{secrets.BASEROW_USER}}
      BASEROW_PW: ${{secrets.BASEROW_PW}}
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --locked

      - name: enrich the data
        run: |
          uv run enrich_places.py
          uv run enrich_persons.py
          uv run fetch_images.py

      - name: dump the data
        run: |
          uv run dump_data.py
          uv run join_tables.py
          uv run make_xml.py
          uv run make_timeline.py
          uv run make_storymap.py

      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Data update from Baserow
